ome/ZarrReader

README.md
pom.xml
src/loci/formats/S3FileSystemStore.java
src/loci/formats/in/ZarrReader.java
src/loci/formats/services/JZarrServiceImpl.java
src/loci/formats/services/ZarrService.java

Initial commits for 0.0.1 ZarrReader to be used as an external reader with Bio-Formats
Any application using Bio-Formats 6.6.0 onwards should be able to use the ZarrReader as an external reader.
The initial reader should be compatible with the latest OME Zarr spec including nested structure.
Note: To update the name of the reader to OMEZarrReader will require a bump to formats-api readers.txt

Initial Prototype ZarrReader

---

src/loci/formats/services/JZarrServiceImpl.java

Not sure when this API changed, but looking upstream the signature is `(String id, Object...keyvalue)`.

Pass 'level' to CompressorFactory

---

pom.xml

see: https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-build/jdk=JDK8,label=testintegration/872/console
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project OMEZarrReader: Failed to deploy artifacts: Could not transfer artifact ome:OMEZarrReader:jar:0.0.1 from/to ome.staging (...nexus/repository/maven-internal/): Failed to transfer file: http://nexus:8081/nexus/repository/maven-internal/ome/OMEZarrReader/0.0.1/OMEZarrReader-0.0.1.jar. Return code is: 400, ReasonPhrase: Repository does not allow updating assets: maven-internal. -> [Help 1]
```

Bump to SNAPSHOT for merge build

---

src/loci/formats/in/ZarrReader.java

With this change (and finding a way to deal with the non-opening of directories) https://github.com/ome/ome_zarr_test_suite/pull/16 passes for:
```
pytest -svxk create-reader
```
Without this change the error is:
```
ZarrReader initializing /private/var/folders/z5/txc_jj6x5l5cm81r56ck1n9c0000gn/T/pytest-of-jamoore/pytest-13/test_create_reader_0/ome_zarr_create.zarr/.zattrs
Exception in thread "main" java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
at loci.formats.in.ZarrReader.parseOmeroMetadata(ZarrReader.java:616)
at loci.formats.in.ZarrReader.initFile(ZarrReader.java:223)
at loci.formats.FormatReader.setId(FormatReader.java:1421)
at …
```

Replace Doubles with Integers

---

pom.xml
src/loci/formats/in/ZarrReader.java
src/test/loci/formats/utests/ZarrReaderTest.java

By adding the testSourceDirectory, the `mvn test`
target can be used in intellij to run tests. This
detected an NPE on `axes` that I've fixed here
though it would be more appropriate for gh-8.

Activate tests in maven

---

.github/workflows/maven.yml
.gitignore
pom.xml
src/loci/formats/S3FileSystemStore.java

`ome.snapshots/ome/OMEZarrReader/0.1.0-SNAPSHOT/` now has two deployments (`mvn deploy`) with these settings:
<details><summary>settings.xml</summary>
```
(base) /opt/ZarrReader $cat ~/.m2/settings.xml
<settings>
<servers>
<server>
<id>ome.snapshots</id>
<username>jamoore</username>
<password>${env.MAVEN_PASSWORD}</password>
</server>
</servers>
<profiles>
<profile>
<id>jamoore</id>
<activation>
<activeByDefault>true</activeByDefault>
</activation>
<repositories>
<repository>
<id>ome.snapshots</id>
<name>OME's Maven Repository</name>
<releases>
<enabled>false</enabled>
<updatePolicy>always</updatePolicy>
<checksumPolicy>warn</checksumPolicy>
</releases>
<snapshots>
<enabled>true</enabled>
<updatePolicy>always</updatePolicy>
<checksumPolicy>warn</checksumPolicy>
</snapshots> …
```

Small jar deployment

---

pom.xml

While working on reviewing #8, I found it hard to identify the version of the commit used to produced a deployed ZarrReader JAR.
This should add the standard build metadata to `MAVEN/MANIFEST.MF` including the commit revision, similarly to what is being done in Bio-Formats

Add standard build metadata to the JAR manifest

---

src/loci/formats/in/ZarrReader.java

Some minor changes to support metadata from 0.3.0 based on https://ngff.openmicroscopy.org/latest/#metadata
Also some handling of datasets that don't have a 5d shape in .zarray
This should support reading of datasets in 0.3.0 and backwards compatibility should be maintained.

ZarrReader: Update to support 0.4.0 datasets

---

src/loci/formats/in/ZarrReader.java

This is a fix that allows for plates to have no acquisitions as this is optional in the spec. Issue was found testing ome-ngff/0.3/idr/idr0094A/7751.zarr/.zattr and should be re-tested with the same dataset along with the idr dataset in 0.4
Fixes #19

ZarrReader: Fix for plates with no acquisitions

---

src/loci/formats/in/ZarrReader.java
src/test/loci/formats/utests/ZarrReaderTest.java

This primarily addresses the issues with incorrect dimensions and incorrect tile size as reported in https://github.com/ome/ZarrReader/issues/17
Testing should be carried out on the datasets mentioned in the related Issue
Fixes #17

Fixes for dimension and tiling issues

---

src/loci/formats/in/ZarrReader.java
src/test/loci/formats/utests/ZarrReaderTest.java

This includes a number of fixes for validation issues reported in https://github.com/ome/ZarrReader/issues/22
It also includes some additional fixes for multi res HCS data discovered during testing.
To test you can run the below and verify that no validation issues are reported and that the resolution levels are properly detected:
`BF_CP=/bio-formats-build/ZarrReader/target/OMEZarrReader-0.1.3-SNAPSHOT-jar-with-dependencies.jar /bio-formats-build/bioformats/tools/showinf -nopix -noflat -omexml /uod/idr/repos/curated/unsupported/ome-ngff/0.3/idr/idr0094A/7751.zarr/.zattrs `
Fixes #22

ZarrReader: HCS validation fixes

---

src/loci/formats/in/ZarrReader.java

This PR adds parsing for the METADATA.ome.xml file produced via bioformats2raw.
Currently the XML is parsed first and any conflicting data in the Zarr attributes will override the XML values.
To test this the best approach would be to take existing OME-TIFF samples, convert them using bf2raw and then compare the OME-XML output from the original to that from the ZarrReader. The ZarrReader is still currently dumping the ngff metadata as annotations, so you will see extra annotations in the converted version.

ZarrReader: Add support for OME-XML from bf2raw

---

.github/workflows/maven.yml

Check that the build is green
Background https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

switch to new output command

---

src/loci/formats/in/ZarrReader.java

This PR is to fix the IDR import errors seen in https://github.com/IDR/idr-metadata/issues/642#issuecomment-1447820599 and other datasets.
Without this PR these datasets would fail due to duplicate keys in the WellSample ImageRefs such as below:
```
cvc-identity-constraint.4.2.2: Duplicate key value [Image:24] found for identity constraint "WellSampleImageRefIDKey" of element "OME".
cvc-identity-constraint.4.2.2: Duplicate key value [Image:39] found for identity constraint "WellSampleImageRefIDKey" of element "OME".
cvc-identity-constraint.4.2.2: Duplicate key value [Image:42] found for identity constraint "WellSampleImageRefIDKey" of element "OME".
cvc-identity-constraint.4.2.2: Duplicate key value [Image:45] found for identity constraint "WellSampleImageRefIDKey" of element "OME". …
```

ZarrReader: Update handling of pre-existing plate metadata

---

src/loci/formats/in/ZarrReader.java
test/loci/formats/utests/ZarrReaderTest.java

This PR is open for the purpose of testing the OMERO symlink issues.
Although we do not want to be using canonical paths within the reader, it seems that doing so when calling jzarr, does seem to resolve the issues and exceptions seen. I would expect a better long term solution would be to resolve this either at the JZarr level or within the ZarrService which call JZarr.

Use canonical path for calls to ZarrService

---

pom.xml

New build of the current main branch from https://github.com/bcdev/jzarr has been copied to https://github.com/zarr-developers/jzarr and the version bumped (a few times). That package is now available on Maven Centra.

Move to dev.zarr:jzarr

---

.github/workflows/maven.yml
pom.xml

Downstream consumers of this reader have been failing to build it over the last few days - see https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-image/372/console or https://github.com/ome/openmicroscopy/actions/runs/6666558502/job/18118363098 with
```
Error:  Failed to execute goal on project OMEZarrReader: Could not resolve dependencies for project ome:OMEZarrReader:jar:0.3.2-SNAPSHOT: Failed to collect dependencies at dev.zarr:jzarr:jar:0.4.0 -> edu.ucar:cdm-core:jar:5.3.3: Failed to read artifact descriptor for edu.ucar:cdm-core:jar:5.3.3: Could not transfer artifact edu.ucar:cdm-core:pom:5.3.3 from/to snap-repo-public (https://snap-build-server.tilaa.cloud/nexus/repository/snap-maven-public/): transfer failed for https://snap-build-server.tilaa.cloud/nexus/repository/snap-mav …
```

Bump dev.zarr:jzarr to 0.4.2

---

src/loci/formats/in/ZarrReader.java

PR is to be used for testing purposes to see if the size of the memo file can be reduced.

Reduce number of fields in memo file

---

.github/workflows/maven.yml
pom.xml

Also deploy the built artifacts directly to `ome.releases` as we did for `ome:bio-formats-examples:7.1.0`

Bump Bio-Formats to version 7.1.0

---

src/loci/formats/in/ZarrReader.java

This was originally driven by an exception seen in https://github.com/IDR/idr-metadata/issues/683#issuecomment-1884665516
The stack trace is as below and is caused by attempting to cast acquisition start time to String when it should be Integer as per the spec (https://github.com/ome/ngff/blob/main/0.4/schemas/plate.schema#L35)
```
Caused by: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.String (java.lang.Long and java.lang.String are in module java.base of loader 'bootstrap')
at loci.formats.in.ZarrReader.parsePlate(ZarrReader.java:755)
at loci.formats.in.ZarrReader.initFile(ZarrReader.java:353)
at loci.formats.FormatReader.setId(FormatReader.java:1443)
at loci.formats.ImageReader.setId(ImageReader.java:849)
at …
```

Update handling and parsing of acquisition metadata

---

pom.xml

Bumping Bio-Formats API to latest release version 7.3.0

Bump formats-api version to 7.3.0

---

src/loci/formats/in/ZarrReader.java
test/loci/formats/utests/ZarrReaderTest.java

There a several commits in different PRs I'd need in order to get a ZarrReader I can work with. This PR brings them together:
- The github action update from #97
- The ClassCastException fix from #95, additionally I fixed the test. 
- The "labels" fix from #98. 
The commits from #95 and #98 are all included, so these PRs could be closed.
#97 is ready, but still on hold, because it will need memo regeneration once released.

Fix issues
