ome/ZarrReader

src/loci/formats/in/ZarrReader.java
Fixes for NPE exceptions and some parsing exceptions for attributes. A full review of the attribute parsing will be needed to bring the reader up to the latest Zarr spec.
=> ZarrReader: NPE and parsing fixes

pom.xml, src/loci/formats/in/ZarrReader.java
Remove dependency leading to build failure
see https://github.com/ome/openmicroscopy/pull/6312#discussion_r852844044
=> Remove dependency

.github/workflows/maven.yml
Update the action v1 is still using set-output
=> upgrade setup-java action. Current version uses set-output

pom.xml
Bump version to 0.3.2-SNAPSHOT
=> Bump version to 0.3.2-SNAPSHOT

pom.xml
Error reported in the bioformats build
=> remove duplicate declaration

.github/workflows/maven.yml
Warning displayed in recent builds
=> Actions update

pom.xml
Bumping Bio-Formats to the latest released version, 7.0.0
=> Bumping Bio-Formats version to 7.0.0

pom.xml
Bumping version to next SNAPSHOT
=> Bump version to 0.4.1-SNAPSHOT

pom.xml
=> Bump version to 0.4.1

.github/workflows/maven.yml, pom.xml
This matches the strategy used in other repositories like Bioformats
=> Review action

.github/workflows/maven.yml
=> add Java 17 to testing matrix

pom.xml
Bumping version to 0.5.0 for release
=> Bump version to 0.5.0

pom.xml
Bumping version to the next SNAPSHOT
=> Bumping version to 0.5.1-SNAPSHOT

CHANGELOG.md
Adding change log entry for 0.5.1 release
=> Add Change Log for 0.5.1

pom.xml
Bumping the Bio-Formats version to the latest 7.3.1
=> Bump Bio-Formats version to 7.3.1

pom.xml
Bumping version to 0.5.2 for release
=> Bump version to 0.5.2

pom.xml
Bumping version to next SNAPSHOT
=> Bump version to 0.5.3-SNAPSHOT

.github/workflows/maven.yml, pom.xml
Update to latest Bio-Formats version.
=> Bump Bio-Formats version to 8.0.1

pom.xml
Roll back to 7.3.1
cc @dominikl
=> Roll back to Bio-Formats 7.3.1

.github/workflows/maven.yml, pom.xml
Fix the upload of the ``jar_with_dependencies``
=> Jar with dependencies

.github/workflows/maven.yml
Upload the artifacts when a tag is pushed
=> Upload the artifacts when a tag is pushed

pom.xml
=> Set version to next snapshot
